global:
  name: consul
  datacenter: dc1
  logLevel: "debug"
  peering:
    enabled: true
  adminPartitions:
    enabled: true
    name: "default"
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true
    httpsOnly: true
  enableConsulNamespaces: true
  acls:
    manageSystemACLs: true
  imagePullSecrets:
    - name: openshift-pull-secret
  openshift:
    enabled: true

meshGateway:
  enabled: true

server:
  enabled: true
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
client:
  enabled: false
  grpc: true
connectInject:
  enabled: true
  default: false
  replicas: 1
  transparentProxy:
    defaultEnabled: false
    defaultOverwriteProbes: false
  consulNamespaces:
    mirroringK8S: true
  apiGateway:
    manageExternalCRDs: true
  cni:
    enabled: true
    logLevel: info
    multus: true
    cniBinDir: /var/lib/cni/bin
    cniNetDir: /etc/kubernetes/cni/net.d
dns:
  enabled: true
  enabledRedirection: true
  type: ClusterIP
ui:
  enabled: true
  ingress:
    enabled: true
    annotations: "route.openshift.io/termination: passthrough"
    pathType: ImplementationSpecific
    hosts:
      - paths:
          - ""
terminatingGateways:
  enabled: false
